config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "posts#index"
  resources :users, only: [:index, :new, :create]
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Post created successfully!"
      redirect_to posts_path
    else
      flash[:error] = "Failed to create the post."
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to posts_path
    else
      flash[:error] = "Failed to create the user."
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    pramas.require(:user).permit(:username, :name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MebersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="user_nav">
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. This cannot be cheese?
           <%= link_to "Logout", destroy_user_session_path, data: {
            turbo_method: :delete,
            turbo_confirm: "Estas seguro de cerrar sesion?"
            } %>
    <% else %>
        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
</div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Lista de posts</h1>

<ul>
  <% @posts.each do |post|%>

    <li>
      <% if user_signed_in? %>
        <p>Author: <%= post.user.email %></p>
      <%end%>
      <h2><%= post[:title] %></h2>
      <p><%= post[:content] %></p>
    </li>
  <%end%>

  <% if user_signed_in? %>
    <%=link_to "Create post", new_post_path %>
    <%=link_to "Ver usuarios", users_path %>
  <%end%>
</ul>

app/views/posts/new.html.erb
<h1>Crear un post</h1>
<%= form_with model: @post do |f| %>
  <div>
    <%= f.label :title, "title: "%>
    <%= f.text_field :title%>
  </div>

  <div>
    <%= f.label :content, "Content: "%>
    <%= f.text_field :content%>
  </div>

  <%= f.submit "Crear post", disable_with: 'Submiting...'%>
<% end %>

app/views/users/index.html.erb
<div>
  <% @users.each do |user|%>
    <h1><%= user[:name] %></h1>
    <p><%= user[:username] %></p>
  <%end%>
</div>

<%= link_to 'Ver posts', posts_path %>